version: 2.1

orbs:
  hello-build: circleci/hello-build@0.0.8

workflows:
  Hello Workflow:
    jobs:
      - hello-build/hello-build:
          name: test
      - hello-build/hello-build:
          name: publish
          requires: 
          - test
          filters:
            branches:
              only: master
